redux and dnd
Evgenia1394/react-burger pull request #4
Opened 2022-05-08 10:10 UTC by Evgenia1394

2022-05-14 19:42 UTC, andryxxa93 requested changes
Проделана большая работа! Правильно реализовали переключение навигации по ингредиентам, правильно используете redux и redux-thunk. 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

1) Не реализована возможность перетаскивания элементов внутри конструктора
2) Счетчик использованных ингредиентов не соответствует макету
3) Необходимо разделить экшоны по файлам, в зависимости от назначения
4) Необходимо разделить редьюсеры по файлам
5) Вынести логику из директории thunk в директорию с экшонами
6) Вынести запросы в отдельные функции и уже потом импортировать в экшоны

В pull request вы найдете комментарии с более подробным описанием проблемы и возможными путями её решения.
В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок.

Удачных правок!

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/modal/modal.jsx
>  const Modal = (props) => {
**Можно лучше**
Модальное окно с данными заказа сейчас располагается не посредине и по размерам не соответствует макету в figma.

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/ingredient-card/ingredient-card.jsx
>  const IngredientCard = (props) => {
**Можно лучше**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/ingredient-card/ingredient-card.jsx
> +            <div className={ingredientCardStyles.wrapper}
**Необходимо исправить**
Здорово, что вы реализовали счетчик ингредиентов, но он должен обновляться внутри компонента с меню ингредиентов, а в конструкторе не должно быть счетчика у ингредиентов. 
Должно быть вот так - 
<img width="689" alt="Снимок экрана 2022-05-14 в 21 48 27" src="https://user-images.githubusercontent.com/60173362/168444680-c78f1e42-57a2-4bb8-b8cb-65cbd41b7dcb.png">

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/modal/modal.jsx
>  const Modal = (props) => {
**Можно лучше**
Картинка подтверждения заказа внутри модального окна не соответствует той, что в макете figma.

2022-05-14 19:42 UTC, andryxxa93 commented on src/services/thunks/thunks.js
> +import {
**Необходимо исправить**
Отдельной директории `thunks`  делать нет необходимости, все что здесь описано необходимо вынести в директорию actions. 
Запрос к api желательно вынести в отдельный файл и просто возвращать результат, а уже вызов запроса делать в actions и там диспатчить нужный экшон в зависимости от результата.
Например:
```
export const getIngredients = () => (dispatch) => {
  dispatch({
    type: GET_INGREDIENTS_REQIEST,
  });
  return getIngredientsApi()
    .then((ingredients) => {
      dispatch({
        type: GET_INGREDIENTS_SUCCESS,
        payload: ingredients,
      });
    })
    .catch((err) => {
      dispatch({
        type: GET_INGREDIENTS_FAILED,
        payload: err,
      });
    });
};
```

2022-05-14 19:42 UTC, andryxxa93 commented on src/services/reducers/rootReducer.js
> +        case GET_ALLINGREDIENTS: {
**Можно лучше**
Усилитель экшона отвечающий за запрос ингредиентов называется - `GET_ALLINGREDIENTS`, а отвечающие за их помещение в стор и обработку ошибки называются иначе. Названию не хватает приставки - REQUEST, которая будет давать однозначное представление о назначении усилителя экшона.

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/app/App.tsx
> +import {ADD_INGREDIENT, INCREASE_COUNT} from "../../services/actions/allActions";
**Можно лучше**
Ненужные импорты желательно удалять

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/app/App.tsx
>  export const baseUrl = 'https://norma.nomoreparties.space/api/';
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести константу с адресом и обработку ответа в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
**Можно лучше**
Такие функции желательно вынести в отдельную директорию - utils.

2022-05-14 19:42 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const notBun = constructorIngredient.filter(ingredient => (ingredient.type !== 'bun')).filter(ingredient => ingredient.count > 0);
**Можно лучше**
Функцию можно упростить и избавиться от лишней фильтрации. Достаточно добавить второе условие в первый фильтр с помощью оператора AND (&&)
`const notBun = constructorIngredient.filter(ingredient => (ingredient.type !== 'bun' &&  ingredient.count > 0))`

2022-05-14 19:42 UTC, andryxxa93 commented on src/services/reducers/rootReducer.js
> +import { combineReducers } from "redux";
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2022-05-14 19:42 UTC, andryxxa93 commented on src/services/actions/allActions.js
> +export const GET_ALLINGREDIENTS = 'GET_ALLINGREDIENTS';
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2022-05-15 17:30 UTC, Evgenia1394 commented on src/components/ingredient-card/ingredient-card.jsx
> +            <div className={ingredientCardStyles.wrapper}
Добрый день! По поводу комментария: Не реализована возможность перетаскивания элементов внутри конструктора - 
Написаны функции для внутреннего перемещения dragStartHandler и dropHandler в файле burger-constructor.jsx
Срабатывают через раз при нажатии на картинку или зону между DragIcon и ConstructorElement,
Не понимаю, почему не срабатывает в остальных случаях, нужна ваша помощь, почему не всегда работает, что переделать?
При перетаскивании из левого контейнера в правый в файле thunks.js при экшене ADD_INGREDIENT добавляю поле order: array.length (=длине массива стейта конструктора)(строка 16).
+ написала отдельный экшен в файле constructor-reducer.js SORT_INGREDIENT, меняющий местами order drag-элемента и order drop-элемента (строка 48). Буду благодарна за помощь и обратную связь!:)

2022-05-16 05:52 UTC, andryxxa93 requested changes
Вы хорошо поработали.  Однако осталось пару моментов, который надо исправить, чтобы я мог принять работу:

1) Счетчик работает некорректно. Он неправильно подсчитывает количество ингредиентов внутри конструктора.
<img width="875" alt="Снимок экрана 2022-05-16 в 08 44 02" src="https://user-images.githubusercontent.com/60173362/168527367-7b3303d5-df35-4600-9e1a-f9a3464d8be6.png">
2) Не корректно работает перетаскивание внутри конструктора. 

По поводу непонятных для вас моментов обратитесь пожалуйста к своему куратору. Он должен подсказать. 

Удачных правок!

2022-05-17 15:12 UTC, andryxxa93 requested changes
Вынужден отклонить работу без потери итерации

Отлично! Проект стал значительно лучше, сортировка и перетаскивание элементов работают как надо! Так держать!

Остался два момента, которыe надо исправить, чтобы работа была принята:
- Исправьте ссылку на pull request в яндекс.практикуме, сейчас она ведёт куда-то не туда. 
- Сейчас при многократном добавлении ингредиента в бургер этот ингредиент не дублируется. Хотя по макету должен. Это хорошо видно на скришоте, последние несколько элементов относятся к одному ингредиенту. 

<img width="814" alt="Снимок экрана 2022-05-17 в 18 08 12" src="https://user-images.githubusercontent.com/60173362/168845067-d7f57ae0-cd60-45c1-b8ed-93453254fe1e.png">

**Можно улучшить**
Уберите console.log из проекта, он нужен только для процесса разработки. 

Удачных правок!

2022-05-18 16:53 UTC, andryxxa93 approved these changes
Вы хорошо поработали. Замечания учтены. Ваша работа принята!
Однако есть ньанс, который не критичен, но я вам рекомендую его исправить.

**Можно улучшить**
Сейчас в конструкторе при многократном добавлении ингредиенты дублируются и это круто. Но теперь есть нюанс с сортировкой. Если добавить 2 одинаковых ингредиента и ещё любой другой, то поместить его между одинаковыми ингредиентами не получится. Связано это с тем, что в сортировке используется _id. Которые у повторяющихся ингредиентов одинаковые. Рекомендую вам использовать для сортировки не _id, а индекс из списка ингредиентов в конструкторе. В action передавать место куда нужно переместить (индекс ингредиента на который переместили другой ингредиент) и откуда (индекс перемещаемого ингредиента).  В редьюсере просто мутируйте массив методом splice с ингредиентами путём добавления перемещаемого ингредиента после ингредиента на который его переместили. Можно это сделать примерно так:
```
const ingredients = [...state.ingredients];
      ingredients.splice(
        action.payload.to,
        0,
        ingredients.splice(action.payload.from, 1)[0]
      );

```

2022-05-18 16:53 UTC, andryxxa93 commented on src/services/reducers/constructor-reducer.jsx
> +            })
**Можно улучшить**
Сейчас в конструкторе при многократном добавлении ингредиенты дублируются и это круто. Но теперь есть нюанс с сортировкой. Если добавить 2 одинаковых ингредиента и ещё любой другой, то поместить его между одинаковыми ингредиентами не получится. Связано это с тем, что в сортировке используется _id. Которые у дублирующих ингредиентов одинаковые. Рекомендую вам использовать для сортировки не _id, а индекс из списка ингредиентов в конструкторе. В action передавать место куда нужно переместить (индекс ингредиента на который переместили другой ингредиент) и откуда (индекс перемещаемого ингредиента).  В редьюсере просто мутируйте массив методом splice с ингредиентами путём добавления перемещаемого ингредиента после ингредиента на который его переместили. Можно это сделать примерно так:
```
const ingredients = [...state.ingredients];
      ingredients.splice(
        action.payload.to,
        0,
        ingredients.splice(action.payload.from, 1)[0]
      );

```

2022-05-24 16:55 UTC, merged